# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:/ProyectosElectronica/Python/Practica personal/Conversor_ui_to_py/conversor_ui_to_py.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 200)
        MainWindow.setMinimumSize(QtCore.QSize(600, 200))
        MainWindow.setMaximumSize(QtCore.QSize(600, 200))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setUnderline(True)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.bt_abrir = QtWidgets.QPushButton(self.centralwidget)
        self.bt_abrir.setMinimumSize(QtCore.QSize(150, 0))
        self.bt_abrir.setMaximumSize(QtCore.QSize(150, 16777215))
        self.bt_abrir.setObjectName("bt_abrir")
        self.horizontalLayout.addWidget(self.bt_abrir)
        self.txt_direccion = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_direccion.setReadOnly(True)
        self.txt_direccion.setObjectName("txt_direccion")
        self.horizontalLayout.addWidget(self.txt_direccion)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.bt_convertir = QtWidgets.QPushButton(self.centralwidget)
        self.bt_convertir.setMinimumSize(QtCore.QSize(150, 0))
        self.bt_convertir.setMaximumSize(QtCore.QSize(150, 16777215))
        self.bt_convertir.setObjectName("bt_convertir")
        self.horizontalLayout_2.addWidget(self.bt_convertir)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.lbl_mensaje = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_mensaje.setFont(font)
        self.lbl_mensaje.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_mensaje.setObjectName("lbl_mensaje")
        self.horizontalLayout_2.addWidget(self.lbl_mensaje)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Conversor de ui a py"))
        self.label.setText(_translate("MainWindow", "Conversor ui to py"))
        self.bt_abrir.setText(_translate("MainWindow", "Abrir Archivo"))
        self.bt_convertir.setText(_translate("MainWindow", "Convertir"))
        self.lbl_mensaje.setText(_translate("MainWindow", "¡Conversión Exitosa!"))
